# Generated by Django 4.1.6 on 2023-06-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('pdesc', models.CharField(max_length=500)),
                ('price', models.FloatField()),
                ('cat', models.CharField(max_length=30)),
            ],
        ),
    ]
